name: aws-terraform-plan
on:
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - 'self-host-runner-ECS/**'

jobs:
  Lint:
    runs-on: [self-hosted, publicAwsEc2Runner]
    defaults:
      run:
        shell: bash
        working-directory: AWS
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: Lint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
        continue-on-error: false

  Format:
    runs-on: [self-hosted, publicAwsEc2Runner]
    defaults:
      run:
        shell: bash
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: setup terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.4.4/terraform_1.4.4_linux_amd64.zip
          unzip terraform_1.4.4_linux_amd64.zip
          mv terraform /usr/local/bin/
      - name: terraform fmt
        id: fmt
        run: terraform fmt
        continue-on-error: false

  Security:
    runs-on: [self-hosted, publicAwsEc2Runner]
    defaults:
      run:
        shell: bash
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: setup tfsec and run
        id: tfsec-setup
        run: |
          wget https://github.com/tfsec/tfsec/releases/download/v0.37.1/tfsec-linux-amd64
          chmod a+x tfsec-linux-amd64
          ./tfsec-linux-amd64
        continue-on-error: false

  TerraformInitValidate:
    runs-on: [self-hosted, publicAwsEc2Runner]
    defaults:
      run:
        shell: bash
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: setup terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.4.4/terraform_1.4.4_linux_amd64.zip
          unzip terraform_1.4.4_linux_amd64.zip
          mv terraform /usr/local/bin/
      - name: terraform init
        id: tf-init
        run: terraform init -upgrade
      # - name: terraform validate
      #   id: validate
      #   run: terraform validate -no-color
      #   continue-on-error: false

  TerraformPlan:
    needs: [Lint, Format, Security, TerraformInitValidate]
    runs-on: [self-hosted, publicAwsEc2Runner]
    defaults:
      run:
        shell: bash
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: setup terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.4.4/terraform_1.4.4_linux_amd64.zip
          unzip terraform_1.4.4_linux_amd64.zip
          mv terraform /usr/local/bin/
      - name: terraform init
        id: tf-init
        run: terraform init -upgrade
      - name: terraform plan
        id: plan
        run: |
          terraform plan >> result.temp
          echo "$(cat result.temp)"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          TF_LOG: DEBUG
        continue-on-error: false